version: '3.1'

networks:
  wordpress_net:
    driver: bridge

services:
  wordpress:
    image: wordpress:latest
    # ports:
    #   - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* Enable SSL */
        define('FORCE_SSL_ADMIN', true);
        if( isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos( $$_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false )
          $$_SERVER['HTTPS'] = 'on';
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - wordpress_net

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - wordpress_data:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - wordpress
    links:
      - wordpress
    networks:
      - wordpress_net

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

volumes:
  wordpress_data:
  db_data:
